#!/usr/bin/ruby
require 'prime'

linenum = 0
fileopen = ARGV.first
text = File.open(fileopen).read
text.gsub!(/\r\n?/, "\n")

text.each_line do |line|
	fact = line.to_i
	if fact % 2 == 0
		puts "#{fact}=#{fact / 2}*2"
	else
		(Prime.each(Math.sqrt(fact).round)).each do |findModulo|
			if fact % findModulo == 0
				puts "#{fact}=#{fact / findModulo}*#{findModulo}"
				break
			end
		end
	end
end
